# Generated by Django 5.1.1 on 2024-09-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=221),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=221),
        ),
        migrations.AlterField(
            model_name='work',
            name='url',
            field=models.CharField(max_length=221),
        ),
    ]
