# Generated by Django 5.1.1 on 2024-09-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_category_title_alter_work_title_alter_work_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='Image',
            new_name='image',
        ),
    ]
