# Generated by Django 5.1.1 on 2024-09-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=221),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_full_name',
            field=models.CharField(max_length=221),
        ),
    ]
